apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: ecr
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: ecr
  policy:
    semver:
      range: 1.0.x #update docker image version pattern here