apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: ecr
  namespace: flux-system
spec:
  image: 746247950449.dkr.ecr.eu-west-1.amazonaws.com/nginx #update ECR repo here
  interval: 1m
  secretRef:
    name: ecr-credentials